testing integration

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -65,6 +65,16 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-node-
 
+      - name: Run main program
+        run: java -cp build/classes/java/main Main
+
+      - name: Verify log file
+        run: |
+          if [ ! -f /tmp/petriNetResults.txt ]; then
+            echo "Log file not found!"
+            exit 1
+          fi
+
       - name: Build with Gradle
         run: ls /tmp && ./gradlew build
 
